version: "3.8"
services:
  chrome:
    image: selenium/node-chrome:4.7.2-20221219
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    ports:
      - "7001:7900"  

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20221219
    volumes:
      - ./videos/chrome:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4    

  firefox:
    image: selenium/node-firefox:4.7.2-20221219
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    ports:
      - "7002:7900"  

  firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20221219
    volumes:
      - ./videos/firefox:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=firefox_video.mp4    
      
  edge:
    image: selenium/node-edge:4.7.2-20221219
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

    ports:
      - "7003:7900"  

  edge_video:
    image: selenium/video:ffmpeg-4.3.1-20221219
    volumes:
      - ./videos/edge:/videos
    depends_on:
      - edge
    environment:
      - DISPLAY_CONTAINER_NAME=edge
      - FILE_NAME=edge_video.mp4


  selenium-hub:
    image: selenium/hub:4.7.2-20221219
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"